# Generated by Django 2.0.7 on 2018-07-26 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 7, 26, 7, 12, 56, 328158, tzinfo=utc))),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('profile_pic', models.TextField(null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 7, 26, 7, 12, 56, 328693, tzinfo=utc))),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2018, 7, 26, 7, 12, 56, 329165, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['created_at', 'updated_at'], name='wishlist_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name', 'gender', 'dob', 'created_at', 'updated_at'], name='user_index'),
        ),
    ]
