# Generated by Django 2.0.7 on 2018-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20180801_1217'),
        ('user', '0010_user_is_staff'),
    ]

    operations = [
    ]
