# Generated by Django 2.0.7 on 2018-08-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('lineitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnLineitemShippingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('return_lineitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='return.ReturnLineitem')),
                ('shipping_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ShippingDetails')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('return_lineitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='return.ReturnLineitem')),
            ],
        ),
        migrations.AddField(
            model_name='returnlineitem',
            name='return_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='return.ReturnOrder'),
        ),
        migrations.AddIndex(
            model_name='returnorderlog',
            index=models.Index(fields=['created_at', 'updated_at'], name='return_order_log_index'),
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['created_at', 'updated_at'], name='return_order_index'),
        ),
        migrations.AddIndex(
            model_name='returnlineitemshippingdetail',
            index=models.Index(fields=['created_at', 'updated_at'], name='return_lineitem_shipp_dtl_idx'),
        ),
        migrations.AddIndex(
            model_name='returnlineitem',
            index=models.Index(fields=['status', 'reason', 'created_at', 'updated_at'], name='return_lineitem_index'),
        ),
    ]
