# Generated by Django 2.0.7 on 2018-07-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'return_lineitem',
            },
        ),
        migrations.CreateModel(
            name='ReturnLineitemShippingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'return_lineitem_shipping_detail',
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'return_order',
            },
        ),
        migrations.CreateModel(
            name='ReturnOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'return_order_log',
            },
        ),
        migrations.AddIndex(
            model_name='returnorderlog',
            index=models.Index(fields=['created_at', 'updated_at'], name='return_order_log_index'),
        ),
        migrations.AddIndex(
            model_name='returnorder',
            index=models.Index(fields=['created_at', 'updated_at'], name='return_order_index'),
        ),
        migrations.AddIndex(
            model_name='returnlineitemshippingdetail',
            index=models.Index(fields=['created_at', 'updated_at'], name='return_lineitem_shipp_dtl_idx'),
        ),
        migrations.AddIndex(
            model_name='returnlineitem',
            index=models.Index(fields=['status', 'reason', 'created_at', 'updated_at'], name='return_lineitem_index'),
        ),
    ]
