# Generated by Django 2.0.7 on 2018-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='returnlineitem',
            name='return_lineitem_index',
        ),
        migrations.RemoveIndex(
            model_name='returnlineitemshippingdetail',
            name='return_lineitem_shipp_dtl_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnorder',
            name='return_order_index',
        ),
        migrations.RemoveIndex(
            model_name='returnorderlog',
            name='return_order_log_index',
        ),
        migrations.RenameField(
            model_name='returnlineitem',
            old_name='lineitem_id',
            new_name='lineitem',
        ),
        migrations.RenameField(
            model_name='returnlineitem',
            old_name='return_order_id',
            new_name='return_order',
        ),
        migrations.RenameField(
            model_name='returnlineitemshippingdetail',
            old_name='return_lineitem_id',
            new_name='return_lineitem',
        ),
        migrations.RenameField(
            model_name='returnlineitemshippingdetail',
            old_name='shipping_detail_id',
            new_name='shipping_detail',
        ),
        migrations.RenameField(
            model_name='returnorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='returnorderlog',
            old_name='return_lineitem_id',
            new_name='return_lineitem',
        ),
        migrations.AlterField(
            model_name='returnlineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnlineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnlineitemshippingdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnlineitemshippingdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnorderlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnorderlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='returnlineitem',
            index=models.Index(fields=['status', 'reason'], name='return_lineitem_index'),
        ),
    ]
