# Generated by Django 2.0.7 on 2018-07-27 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('return', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnlineitem',
            name='lineitem_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlineitem',
            name='return_order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='return.ReturnOrder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlineitemshippingdetail',
            name='return_lineitem_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='return.ReturnLineitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlineitemshippingdetail',
            name='shipping_detail_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.ShippingDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnorder',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnorderlog',
            name='return_lineitem_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='return.ReturnLineitem'),
            preserve_default=False,
        ),
    ]
