# Generated by Django 2.0.7 on 2018-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='status',
            field=models.CharField(choices=[('GN', 'Generated'), ('IP', 'In Progress'), ('CN', 'Canceled'), ('RJ', 'Rejected'), ('CM', 'Complete')], default='GN', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('G', 'Generated'), ('PC', 'Partially Complete'), ('C', 'Complete')], default='G', max_length=2),
        ),
    ]
