# Generated by Django 2.0.7 on 2018-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return', '0002_auto_20180727_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnlineitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='returnlineitemshippingdetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
