# Generated by Django 2.0.7 on 2018-08-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180808_1603'),
        ('return', '0002_auto_20180807_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnLineitem',
            new_name='Lineitem',
        ),
        migrations.RenameModel(
            old_name='ReturnLineitemShippingDetail',
            new_name='LineitemShippingDetail',
        ),
        migrations.RenameModel(
            old_name='ReturnOrder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='ReturnOrderLog',
            new_name='OrderLog',
        ),
    ]
