# Generated by Django 2.0.7 on 2018-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('return', '0003_auto_20180731_0704'),
        ('return', '0003_auto_20180730_1147'),
    ]

    operations = [
    ]
