# Generated by Django 2.0.7 on 2018-07-26 10:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cart_processed', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_order_generated', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line_shiping_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'line_shiping_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shiping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('gift_wrap_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lineitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineitem_tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lineitem_tax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('shipping_name', models.TextField()),
                ('shipping_address_line', models.TextField()),
                ('shipping_city', models.CharField(max_length=60)),
                ('shipping_state', models.CharField(max_length=60)),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('billing_name', models.TextField()),
                ('billing_address_line', models.TextField()),
                ('billing_city', models.CharField(max_length=60)),
                ('billing_state', models.CharField(max_length=60)),
                ('billing_pincode', models.CharField(max_length=10)),
                ('totoal_shipping_cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shiping_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courior_name', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=50)),
                ('deliverd_date', models.DateField(blank=True, null=True)),
                ('tracking_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shiping_details',
                'managed': False,
            },
        ),
    ]
