# Generated by Django 2.0.7 on 2018-08-03 10:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cart_processed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('is_order_generated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shiping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('gift_wrap_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineitemTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_name', models.CharField(max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='LineShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('shipping_name', models.TextField()),
                ('shipping_address_line', models.TextField()),
                ('shipping_city', models.CharField(max_length=60)),
                ('shipping_state', models.CharField(max_length=60)),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('billing_name', models.TextField()),
                ('billing_address_line', models.TextField()),
                ('billing_city', models.CharField(max_length=60)),
                ('billing_state', models.CharField(max_length=60)),
                ('billing_pincode', models.CharField(max_length=10)),
                ('totoal_shipping_cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courior_name', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=50)),
                ('deliverd_date', models.DateField(blank=True, null=True)),
                ('tracking_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='shippingdetails',
            index=models.Index(fields=['created_at', 'updated_at', 'tracking_number', 'deliverd_date', 'courior_name'], name='shiping_details_index'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['created_at', 'updated_at'], name='payment_method_index'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='lineitem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
        ),
    ]
