# Generated by Django 2.0.7 on 2018-07-26 12:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cart_processed', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_order_generated', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart_product',
            },
        ),
        migrations.CreateModel(
            name='Line_shiping_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'line_shiping_details',
            },
        ),
        migrations.CreateModel(
            name='Lineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shiping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('gift_wrap_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lineitem',
            },
        ),
        migrations.CreateModel(
            name='Lineitem_tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'lineitem_tax',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('shipping_name', models.TextField()),
                ('shipping_address_line', models.TextField()),
                ('shipping_city', models.CharField(max_length=60)),
                ('shipping_state', models.CharField(max_length=60)),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('billing_name', models.TextField()),
                ('billing_address_line', models.TextField()),
                ('billing_city', models.CharField(max_length=60)),
                ('billing_state', models.CharField(max_length=60)),
                ('billing_pincode', models.CharField(max_length=10)),
                ('totoal_shipping_cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Order_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_log',
            },
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Shiping_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courior_name', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=50)),
                ('deliverd_date', models.DateField(blank=True, null=True)),
                ('tracking_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shiping_details',
            },
        ),
        migrations.AddIndex(
            model_name='shiping_details',
            index=models.Index(fields=['created_at', 'updated_at', 'tracking_number', 'deliverd_date', 'courior_name'], name='shiping_details_index'),
        ),
        migrations.AddIndex(
            model_name='payment_method',
            index=models.Index(fields=['created_at', 'updated_at'], name='payment_method_index'),
        ),
        migrations.AddField(
            model_name='order_log',
            name='lineitem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Payment_method'),
        ),
        migrations.AddField(
            model_name='lineitem_tax',
            name='lineitem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='line_shiping_details',
            name='lineitem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
        ),
        migrations.AddField(
            model_name='line_shiping_details',
            name='shiping_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Shiping_details'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cart'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at', 'updated_at'], name='cart_index'),
        ),
        migrations.AddIndex(
            model_name='order_log',
            index=models.Index(fields=['created_at', 'updated_at'], name='order_log_index'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'updated_at', 'shipping_pincode', 'billing_pincode', 'shipping_city', 'shipping_state', 'billing_city', 'billing_state'], name='order_index'),
        ),
        migrations.AddIndex(
            model_name='lineitem_tax',
            index=models.Index(fields=['created_at', 'updated_at', 'tax_name'], name='lineitem_tax_index'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['created_at', 'updated_at', 'status'], name='lineitem_index'),
        ),
        migrations.AddIndex(
            model_name='line_shiping_details',
            index=models.Index(fields=['created_at', 'updated_at'], name='line_shiping_details_index'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['created_at', 'updated_at'], name='cart_product_index'),
        ),
    ]
