# Generated by Django 2.0.7 on 2018-07-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
        ('seller', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='seller_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='seller_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.Address'),
            preserve_default=False,
        ),
    ]
