# Generated by Django 2.0.7 on 2018-08-28 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20180828_1625'),
        ('order', '0002_auto_20180803_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='lineitemtax',
            name='lineitem_id',
        ),
        migrations.RemoveField(
            model_name='lineshippingdetails',
            name='lineitem_id',
        ),
        migrations.RemoveField(
            model_name='lineshippingdetails',
            name='shiping_details_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='lineitemtax',
            index=models.Index(fields=['tax_name'], name='lineitem_tax_index'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_pincode', 'billing_pincode', 'shipping_city', 'shipping_state', 'billing_city', 'billing_state'], name='order_index'),
        ),
    ]
