# Generated by Django 2.0.7 on 2018-08-03 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20180803_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderlog',
            index=models.Index(fields=['created_at', 'updated_at'], name='order_log_index'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'updated_at', 'shipping_pincode', 'billing_pincode', 'shipping_city', 'shipping_state', 'billing_city', 'billing_state'], name='order_index'),
        ),
        migrations.AddIndex(
            model_name='lineshippingdetails',
            index=models.Index(fields=['created_at', 'updated_at'], name='line_shiping_details_index'),
        ),
        migrations.AddIndex(
            model_name='lineitemtax',
            index=models.Index(fields=['created_at', 'updated_at', 'tax_name'], name='lineitem_tax_index'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['created_at', 'updated_at', 'status'], name='lineitem_index'),
        ),
        migrations.AddIndex(
            model_name='cartproduct',
            index=models.Index(fields=['created_at', 'updated_at'], name='cart_product_index'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at', 'updated_at'], name='cart_index'),
        ),
    ]
