# Generated by Django 2.0.7 on 2018-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180803_1548'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_index',
        ),
        migrations.RemoveIndex(
            model_name='cartproduct',
            name='cart_product_index',
        ),
        migrations.RemoveIndex(
            model_name='lineitem',
            name='lineitem_index',
        ),
        migrations.RemoveIndex(
            model_name='lineitemtax',
            name='lineitem_tax_index',
        ),
        migrations.RemoveIndex(
            model_name='lineshippingdetails',
            name='line_shiping_details_index',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_index',
        ),
        migrations.RemoveIndex(
            model_name='orderlog',
            name='order_log_index',
        ),
        migrations.RemoveIndex(
            model_name='paymentmethod',
            name='payment_method_index',
        ),
        migrations.RemoveIndex(
            model_name='shippingdetails',
            name='shiping_details_index',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='lineitemtax',
            old_name='lineitem_id',
            new_name='lineitem',
        ),
        migrations.RenameField(
            model_name='lineshippingdetails',
            old_name='lineitem_id',
            new_name='lineitem',
        ),
        migrations.RenameField(
            model_name='lineshippingdetails',
            old_name='shiping_details_id',
            new_name='shipping_details',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method_id',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='orderlog',
            old_name='lineitem_id',
            new_name='lineitem',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lineitemtax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lineitemtax',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lineshippingdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lineshippingdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='lineitemtax',
            index=models.Index(fields=['tax_name'], name='lineitem_tax_index'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_pincode', 'billing_pincode', 'shipping_city', 'shipping_state', 'billing_city', 'billing_state'], name='order_index'),
        ),
        migrations.AddIndex(
            model_name='shippingdetails',
            index=models.Index(fields=['tracking_number', 'deliverd_date', 'courior_name'], name='shiping_details_index'),
        ),
    ]
