# Generated by Django 2.0.7 on 2018-08-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180803_1548'),
        ('order', '0004_auto_20180813_1509'),
    ]

    operations = [
    ]
