# Generated by Django 2.0.7 on 2018-09-11 09:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_20180829_1551'),
        ('order', '0004_merge_20180829_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='seller',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product_seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
