# Generated by Django 2.0.7 on 2018-08-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180816_0949'),
        ('order', '0002_auto_20180803_1548'),
    ]

    operations = [
    ]
