# Generated by Django 2.0.7 on 2018-08-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_20180816_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='lineitemtax',
            name='lineitem_id',
        ),
        migrations.RemoveField(
            model_name='lineshippingdetails',
            name='lineitem_id',
        ),
        migrations.RemoveField(
            model_name='lineshippingdetails',
            name='shiping_details_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method_id',
        ),
    ]
