# Generated by Django 2.0.7 on 2018-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiping_contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
