# Generated by Django 2.0.7 on 2018-09-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180911_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_contact_no',
            new_name='shipping_contact_no',
        ),
    ]
