# Generated by Django 2.0.7 on 2018-08-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_merge_20180829_1551'),
        ('order', '0006_auto_20180816_1005'),
    ]

    operations = [
    ]
