# Generated by Django 2.0.7 on 2018-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180731_0705'),
        ('order', '0005_auto_20180731_0704'),
    ]

    operations = [
    ]
