# Generated by Django 2.0.7 on 2018-09-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180911_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemtax',
            old_name='discount',
            new_name='percentage',
        ),
    ]
