# Generated by Django 2.0.7 on 2018-09-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180911_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='discount',
        ),
    ]
