# Generated by Django 2.0.7 on 2018-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_lineitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Debit/Credit Card', 'Debit/Credit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], default='Cash', max_length=20),
        ),
    ]
