# Generated by Django 2.0.7 on 2018-07-27 07:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_auto_20180727_0744'),
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_for_order', models.BooleanField()),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('for_new_user', models.BooleanField()),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('max_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='OrderOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'order_offer',
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'product_offer',
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_redeemed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_offer',
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['created_at', 'updated_at', 'valid_from', 'valid_upto', 'name'], name='offer_index'),
        ),
        migrations.AddIndex(
            model_name='useroffer',
            index=models.Index(fields=['created_at', 'updated_at'], name='user_offer_index'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['created_at', 'updated_at'], name='product_offer_index'),
        ),
        migrations.AddIndex(
            model_name='orderoffer',
            index=models.Index(fields=['created_at', 'updated_at'], name='order_offer_index'),
        ),
    ]
