# Generated by Django 2.0.7 on 2018-08-03 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('order', '0002_auto_20180803_1548'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroffer',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='offers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='offers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='offerlineitem',
            name='lineitem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
        ),
        migrations.AddField(
            model_name='offerlineitem',
            name='offers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['created_at', 'updated_at', 'valid_from', 'valid_upto', 'name'], name='offer_index'),
        ),
        migrations.AddIndex(
            model_name='useroffer',
            index=models.Index(fields=['created_at', 'updated_at'], name='user_offer_index'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['created_at', 'updated_at'], name='product_offer_index'),
        ),
        migrations.AddIndex(
            model_name='orderoffer',
            index=models.Index(fields=['created_at', 'updated_at'], name='order_offer_index'),
        ),
        migrations.AddIndex(
            model_name='offerlineitem',
            index=models.Index(fields=['created_at', 'updated_at'], name='offer_lineitem_index'),
        ),
    ]
