# Generated by Django 2.0.7 on 2018-07-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0003_auto_20180727_0744'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_redeemed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'offer_lineitem',
            },
        ),
        migrations.AddIndex(
            model_name='offerlineitem',
            index=models.Index(fields=['created_at', 'updated_at'], name='offer_lineitem_index'),
        ),
    ]
