# Generated by Django 2.0.7 on 2018-08-28 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20180828_1203'),
        ('product', '0002_auto_20180828_1203'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlineitem',
            name='lineitem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerlineitem',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffer',
            name='offers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useroffer',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['valid_from', 'valid_upto', 'name'], name='offer_index'),
        ),
    ]
