# Generated by Django 2.0.7 on 2018-08-16 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20180816_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='offers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
        ),
        migrations.AddField(
            model_name='orderoffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='offerlineitem',
            name='lineitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem'),
        ),
        migrations.AddField(
            model_name='offerlineitem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['valid_from', 'valid_upto', 'name'], name='offer_index'),
        ),
    ]
