# Generated by Django 2.0.7 on 2018-07-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
