# Generated by Django 2.0.7 on 2018-07-30 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20180730_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
