# Generated by Django 2.0.7 on 2018-09-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_merge_20180829_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroffer',
            old_name='order',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
