# Generated by Django 2.0.7 on 2018-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20180731_0704'),
        ('offer', '0004_auto_20180731_0705'),
    ]

    operations = [
    ]
