# Generated by Django 2.0.7 on 2018-08-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_auto_20180731_0705'),
        ('offer', '0003_auto_20180731_0704'),
    ]

    operations = [
    ]
