# Generated by Django 2.0.7 on 2018-08-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_20180731_1648'),
        ('offer', '0005_merge_20180731_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLineitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Lineitem')),
                ('offers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
            ],
            options={
                'db_table': 'offer_lineitem',
            },
        ),
        migrations.AddIndex(
            model_name='offerlineitem',
            index=models.Index(fields=['created_at', 'updated_at'], name='offer_lineitem_index'),
        ),
    ]
