# Generated by Django 2.0.7 on 2018-09-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20180914_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='offers',
            new_name='offer',
        ),
    ]
