# Generated by Django 2.0.7 on 2018-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_merge_20180731_1648'),
        ('offer', '0005_merge_20180801_1217'),
    ]

    operations = [
    ]
