# Generated by Django 2.0.7 on 2018-10-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20180914_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='amount_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
