# Generated by Django 2.0.7 on 2018-10-08 05:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_auto_20181008_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), blank=True, null=True, size=None),
        ),
    ]
