# Generated by Django 2.0.7 on 2018-07-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180726_0728'),
        ('seller', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='productseller',
            name='seller_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'created_at', 'updated_at'], name='review_index'),
        ),
    ]
