# Generated by Django 2.0.7 on 2018-08-28 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20180828_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytax',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorytax',
            name='tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Tax'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfeature',
            name='feature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Feature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productseller',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productseller',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='brand_index'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name', 'created_at', 'updated_at'], name='category_index'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['name'], name='feature_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_index'),
        ),
        migrations.AddIndex(
            model_name='productfeature',
            index=models.Index(fields=['value'], name='product_feature_index'),
        ),
        migrations.AddIndex(
            model_name='productseller',
            index=models.Index(fields=['discount', 'max_delivery_days', 'min_delivery_days'], name='product_seller_index'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='review_index'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['name'], name='tax_index'),
        ),
    ]
