# Generated by Django 2.0.7 on 2018-07-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytax',
            name='percentage',
        ),
    ]
