# Generated by Django 2.0.7 on 2018-08-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180816_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
