# Generated by Django 2.0.7 on 2018-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_categorytax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default='', max_digits=4),
        ),
    ]
