# Generated by Django 2.0.7 on 2018-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_20180829_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='productseller',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=19),
            preserve_default=False,
        ),
    ]
