# Generated by Django 2.0.7 on 2018-08-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180807_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytax',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productfeature',
            old_name='feature_id',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='productfeature',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productseller',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productseller',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
