# Generated by Django 2.0.7 on 2018-09-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180906_1527'),
        ('product', '0004_auto_20180912_1433'),
    ]

    operations = [
    ]
