# Generated by Django 2.0.7 on 2018-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180730_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productseller',
            name='quentity',
            field=models.PositiveIntegerField(),
        ),
    ]
