# Generated by Django 2.0.7 on 2018-08-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180807_1054'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_index',
        ),
        migrations.RemoveIndex(
            model_name='categorytax',
            name='category_tax_index',
        ),
        migrations.RemoveIndex(
            model_name='feature',
            name='feature_index',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_index',
        ),
        migrations.RemoveIndex(
            model_name='productfeature',
            name='product_feature_index',
        ),
        migrations.RemoveIndex(
            model_name='productseller',
            name='product_seller_index',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_index',
        ),
        migrations.RemoveIndex(
            model_name='tax',
            name='tax_index',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='wishlist_index',
        ),
        migrations.RenameField(
            model_name='categorytax',
            old_name='tax_id',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='brand_index'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['name'], name='feature_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_index'),
        ),
        migrations.AddIndex(
            model_name='productfeature',
            index=models.Index(fields=['value'], name='product_feature_index'),
        ),
        migrations.AddIndex(
            model_name='productseller',
            index=models.Index(fields=['discount', 'max_delivery_days', 'min_delivery_days'], name='product_seller_index'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='review_index'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['name'], name='tax_index'),
        ),
    ]
