# Generated by Django 2.0.7 on 2018-08-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_20180829_1551'),
        ('product', '0005_auto_20180823_1716'),
    ]

    operations = [
    ]
