# Generated by Django 2.0.7 on 2018-09-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_merge_20180918_1740'),
        ('product', '0005_merge_20180919_1128'),
    ]

    operations = [
    ]
