# Generated by Django 2.0.7 on 2018-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_merge_20180731_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productseller',
            old_name='quentity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
