# Generated by Django 2.0.7 on 2018-10-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20181008_1225'),
        ('product', '0007_auto_20181008_1415'),
    ]

    operations = [
    ]
