# Generated by Django 2.0.7 on 2018-08-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180801_1055'),
    ]

    operations = [
    ]
