# Generated by Django 2.0.7 on 2018-08-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_merge_20180801_1217'),
        ('product', '0009_merge_20180802_0721'),
    ]

    operations = [
    ]
