# Generated by Django 2.0.7 on 2018-10-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_average_rating'),
        ('product', '0010_product_average_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productseller',
            unique_together={('product', 'seller')},
        ),
    ]
