# Generated by Django 2.0.7 on 2018-10-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20181017_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.ImageField(upload_to='product/images/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
