# Generated by Django 2.0.7 on 2018-08-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_merge_20180829_1551'),
        ('contact', '0003_auto_20180816_0949'),
    ]

    operations = [
    ]
