# Generated by Django 2.0.7 on 2018-09-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_merge_20180829_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
