# Generated by Django 2.0.7 on 2018-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_address_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_no',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
