# Generated by Django 2.0.7 on 2018-07-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
