# Generated by Django 2.0.7 on 2018-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20180803_1548'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='address_index',
        ),
        migrations.RemoveIndex(
            model_name='seller',
            name='seller_index',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['pincode', 'state', 'city'], name='address_index'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['company_name'], name='seller_index'),
        ),
    ]
