# Generated by Django 2.0.7 on 2018-08-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20180828_1625'),
    ]

    operations = [
    ]
