# Generated by Django 2.0.7 on 2018-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_merge_20180829_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Active', 'Active'), ('InActive', 'InActive')], default='InProgress', max_length=20),
        ),
    ]
