# Generated by Django 2.0.7 on 2018-08-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20180807_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
