# Generated by Django 2.0.7 on 2018-10-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20181010_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
