# Generated by Django 2.0.7 on 2018-10-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20181009_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='selleruser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='seller',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Active', 'Active'), ('InActive', 'InActive')], default='InProgress', max_length=20),
        ),
    ]
