# Generated by Django 2.0.7 on 2018-08-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20180801_1545'),
        ('seller', '0004_merge_20180801_1519'),
    ]

    operations = [
    ]
